import TopMenu from "@/components/TopMenu";
import "./globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/ NextAuthProvider";

const ibm = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Co-working Space Reservation",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nextAuthSession = await getServerSession(authOptions);
  return (
    <html lang="en" className="bg-bg">
      <body className={ibm.className}>
        <NextAuthProvider session={nextAuthSession}>
          <div className="my-16">
            <TopMenu />
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
